config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from courseinfo import urls as courseinfo_urls

urlpatterns = [
    path('', TemplateView.as_view(template_name='pages/home.html'), name='home'),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # User management
    path('users/', include('ez_university.users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),

    # Custom urls includes go here
    path('courseinfo/', include(courseinfo_urls, namespace='courseinfo')),  # We should change this to 'courses/'


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
        path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

courseinfo/urls.py
from django.urls import path
from .views import (InstructorList,
                    InstructorDetailView,
                    InstructorCreate, InstructorUpdate, InstructorDelete,
                    SectionList,
                    SectionDetailView,
                    SectionCreate, SectionUpdate, SectionDelete,
                    CourseList,
                    CourseDetailView,
                    CourseCreate, CourseUpdate, CourseDelete,
                    SemesterList,
                    SemesterDetailView,
                    SemesterCreate, SemesterUpdate, SemesterDelete,
                    StudentList,
                    StudentDetailView,
                    StudentCreate, StudentUpdate, StudentDelete,
                    Courseinfo)

app_name = 'courseinfo'
urlpatterns = [
    path('', Courseinfo.as_view(), name='courseinfo_home'),

    path('instructor/', InstructorList.as_view(), name='instructor_list'),

    path('instructor/create/', InstructorCreate.as_view(), name='instructor_create'),

    path('instructor/<slug>/remove/', InstructorDelete.as_view(), name='instructor_remove'),

    path('instructor/<slug>/update/', InstructorUpdate.as_view(), name='instructor_update'),

    path('instructor/<slug>/', InstructorDetailView.as_view(), name='instructor_detail'),

    path('section/', SectionList.as_view(), name='section_list'),

    path('section/create/', SectionCreate.as_view(), name='section_create'),

    path('section/<slug>/remove/', SectionDelete.as_view(), name='section_remove'),

    path('section/<slug>/update/', SectionUpdate.as_view(), name='section_update'),

    path('section/<slug>/', SectionDetailView.as_view(), name='section_detail'),

    path('course/', CourseList.as_view(), name='course_list'),

    path('course/create/', CourseCreate.as_view(), name='course_create'),

    path('course/<slug>/remove/', CourseDelete.as_view(), name='course_remove'),

    path('course/<slug>/update/', CourseUpdate.as_view(), name='course_update'),

    path('course/<slug>/', CourseDetailView.as_view(), name='course_detail'),

    path('semester/', SemesterList.as_view(), name='semester_list'),

    path('semester/create/', SemesterCreate.as_view(), name='semester_create'),

    path('semester/<slug>/remove/', SemesterDelete.as_view(), name='semester_remove'),

    path('semester/<slug>/update/', SemesterUpdate.as_view(), name='semester_update'),

    path('semester/<slug>/', SemesterDetailView.as_view(), name='semester_detail'),

    path('student/', StudentList.as_view(), name='student_list'),

    path('student/create/', StudentCreate.as_view(), name='student_create'),

    path('student/<slug>/remove/', StudentDelete.as_view(), name='student_remove'),

    path('student/<slug>/update/', StudentUpdate.as_view(), name='student_update'),

    path('student/<slug>/', StudentDetailView.as_view(), name='student_detail'),
]

ez_university/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

ez_university/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

ez_university/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

ez_university/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

ez_university/templates/base.html
{% load static i18n compress%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}EZ_university{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}

      <!-- Your stuff: Third-party CSS libraries go here -->
      {% compress css %}
      <!-- This file stores project-specific CSS -->

      <link href="{% static 'css/project.css' %}" rel="stylesheet">
      <link rel="stylesheet" type="text/css"
            href="{% static 'coursinfo/normalize.css' %}">
      <link rel="stylesheet" type="text/css"
            href="{% static 'courseinfo/skeleton.css' %}">
      <link rel="stylesheet" type="text/css"
            href="{% static 'courseinfo/style.css' %}">

      {% endcompress %}

    {% endblock %}

  </head>

  <body>
    <div class="container">
    <header class="row">
        <div class="offset-by-one ten columns">
            <h1 class="logo">EZ University</h1>
            <h2>Course Information System</h2>
        </div>
    </header>
    <nav>
      <ul>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'courseinfo:instructor_list' %}">Instructors</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'courseinfo:section_list' %}">Sections</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'courseinfo:course_list' %}">Courses</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'courseinfo:semester_list' %}">Semesters</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'courseinfo:student_list' %}">Students</a>
          </li>

          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
          </li>

          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
          </li>

        {% else %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
          </li>
        {% endif %}
        <li class="nav-item">
          {# This link any user should be able to see, even if they are not logged in#}
          <a id="log-in-link" class="nav-link" href="{% url 'about' %}">{% trans "About" %}</a>
        </li>
      </ul>
    </nav>
    {% if messages %}
        <div class="row">
            <div class="twelve columns">
                <ul class="messages">
                    {% for message in messages %}
                        {% if message.tags %}
                            <li class="{{ message.tags }}">
                                {% else %}
                            <li>
                        {% endif %}
                    {{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}
    <main>
    {% block content %}
      <div class="row">
        <section class="eight columns">
          {% block org_content %}
            This is default content!
          {% endblock %}
        </section>
        <section class="desktop four columns">
          {% block create_button %}{% endblock %}
        </section>
      </div>
      <div class="row">
        <div class="twelve columns">
          {% block content_footer %}{% endblock %}
        </div>
      </div>
    {% endblock %}
    </main>
  </div><!-- container -->

  <footer>
    <p>
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
            <img alt="Creative Commons License" style="border-width:0"
                 src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"/>
        </a><br/><span property="dct:title">EZ University Tutorial Examples and Code</span>
        by
        <a href="https://www.ligent.net" property="cc:attributionName"
           rel="cc:attributionURL">Ligent, LLC</a> are licensed under a
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike
            4.0 International License</a>.
    </p>
    <p>Portions of the EZ University code are based upon code from
        <a href="https://django-unleashed.com">Django Unleashed</a>,
        <a href="http://getskeleton.com/">Skeleton</a>, and
        <a href="https://necolas.github.io/normalize.css/">Normalize.css</a> and
        are subject to the intellectual property rights restrictions of those works.
    </p>
  </footer>



    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>