config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from courseinfo import urls as courseinfo_urls

urlpatterns = [
    path('', TemplateView.as_view(template_name='pages/home.html'), name='home'),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # User management
    path('users/', include('ez_university.users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),

    # Custom urls includes go here
    path('courseinfo/', include(courseinfo_urls, namespace='courseinfo')),  # We should change this to 'courses/'


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
        path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

courseinfo/urls.py
from django.urls import path
from .views import (InstructorList,
                    InstructorDetailView,
                    InstructorCreate, InstructorUpdate, InstructorDelete,
                    SectionList,
                    SectionDetailView,
                    SectionCreate, SectionUpdate, SectionDelete,
                    CourseList,
                    CourseDetailView,
                    CourseCreate, CourseUpdate, CourseDelete,
                    SemesterList,
                    SemesterDetailView,
                    SemesterCreate, SemesterUpdate, SemesterDelete,
                    StudentList,
                    StudentDetailView,
                    StudentCreate, StudentUpdate, StudentDelete,
                    Courseinfo)

app_name = 'courseinfo'
urlpatterns = [
    path('', Courseinfo.as_view(), name='courseinfo_home'),

    path('instructor/', InstructorList.as_view(), name='instructor_list'),

    path('instructor/create/', InstructorCreate.as_view(), name='instructor_create'),

    path('instructor/<slug>/remove/', InstructorDelete.as_view(), name='instructor_remove'),

    path('instructor/<slug>/update/', InstructorUpdate.as_view(), name='instructor_update'),

    path('instructor/<slug>/', InstructorDetailView.as_view(), name='instructor_detail'),

    path('section/', SectionList.as_view(), name='section_list'),

    path('section/create/', SectionCreate.as_view(), name='section_create'),

    path('section/<slug>/remove/', SectionDelete.as_view(), name='section_remove'),

    path('section/<slug>/update/', SectionUpdate.as_view(), name='section_update'),

    path('section/<slug>/', SectionDetailView.as_view(), name='section_detail'),

    path('course/', CourseList.as_view(), name='course_list'),

    path('course/create/', CourseCreate.as_view(), name='course_create'),

    path('course/<slug>/remove/', CourseDelete.as_view(), name='course_remove'),

    path('course/<slug>/update/', CourseUpdate.as_view(), name='course_update'),

    path('course/<slug>/', CourseDetailView.as_view(), name='course_detail'),

    path('semester/', SemesterList.as_view(), name='semester_list'),

    path('semester/create/', SemesterCreate.as_view(), name='semester_create'),

    path('semester/<slug>/remove/', SemesterDelete.as_view(), name='semester_remove'),

    path('semester/<slug>/update/', SemesterUpdate.as_view(), name='semester_update'),

    path('semester/<slug>/', SemesterDetailView.as_view(), name='semester_detail'),

    path('student/', StudentList.as_view(), name='student_list'),

    path('student/create/', StudentCreate.as_view(), name='student_create'),

    path('student/<slug>/remove/', StudentDelete.as_view(), name='student_remove'),

    path('student/<slug>/update/', StudentUpdate.as_view(), name='student_update'),

    path('student/<slug>/', StudentDetailView.as_view(), name='student_detail'),
]

courseinfo/forms.py
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from courseinfo.models import (Instructor, Section, Course,
                               Semester, Student)


class InstructorForm(ModelForm):
    class Meta:
        model = Instructor
        fields = ['first_name', 'last_name']

    def __init__(self, *args, **kwargs):
        super(InstructorForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Submit Instructor'))

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()


class SectionForm(ModelForm):
    class Meta:
        model = Section
        fields = ['section_name',
                  'semester',
                  'course',
                  'instructors',
                  'students']

    def __init__(self, *args, **kwargs):
        super(SectionForm, self).__init__(*args, **kwargs)
        self.fields['students'].required = False
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Submit Section'))


class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = ['course_number',
                  'course_name']

    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Submit Course'))


class SemesterForm(ModelForm):
    class Meta:
        model = Semester
        fields = ['calendar_period', 'year']

    def __init__(self, *args, **kwargs):
        super(SemesterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Submit Semester'))


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ['first_name',
                  'last_name',
                  'nick_name']

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Submit Student'))

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()

    def clean_nick_name(self):
        return self.cleaned_data['nick_name'].strip()

courseinfo/views.py
from django.views.generic import (ListView, TemplateView, DetailView,
                                  CreateView, UpdateView, DeleteView)
from django.urls import reverse_lazy
from .models import Instructor, Section, Course, Semester, Student
from .forms import (InstructorForm, SectionForm, CourseForm,
                    SemesterForm, StudentForm)
from .utils import CourseActionMixin, ValidateUnconnectedSectionsDeleteMixin
from django.contrib.auth.mixins import LoginRequiredMixin


GENERIC_CRISPY_FORM_PATH = 'courseinfo/generic_crispy_form.html'
GENERIC_DELETE_TEMPLATE_PATH = 'courseinfo/generic_confirm_delete.html'
GENERIC_FAILED_DELETE_TEMPLATE_PATH = 'courseinfo/generic_failed_delete.html'


class Courseinfo(LoginRequiredMixin, TemplateView):
    template_name = 'courseinfo/courseinfo_base.html'


class InstructorList(LoginRequiredMixin, ListView):
    model = Instructor
    context_object_name = 'instructor_list'
    paginate_by = 5
    queryset = Instructor.objects.all()


class InstructorDetailView(LoginRequiredMixin, DetailView):
    model = Instructor

    def get_context_data(self, **kwargs):
        kwargs['sections'] = self.get_object().sections.all()
        return super(InstructorDetailView, self).get_context_data(**kwargs)


class InstructorCreate(LoginRequiredMixin, CourseActionMixin, CreateView):
    model = Instructor
    success_msg = "Instructor Created!"
    form_class = InstructorForm
    template_name = GENERIC_CRISPY_FORM_PATH

    def get_context_data(self, **kwargs):
        context = super(InstructorCreate, self).get_context_data(**kwargs)
        context['page_title'] = 'Create Instructor'
        return context


class InstructorUpdate(LoginRequiredMixin, CourseActionMixin, UpdateView):
    model = Instructor
    success_msg = "Instructor Updated!"
    form_class = InstructorForm
    template_name = GENERIC_CRISPY_FORM_PATH

    def get_context_data(self, **kwargs):
        context = super(InstructorUpdate, self).get_context_data(**kwargs)
        context['page_title'] = 'Update Instructor'
        return context


class InstructorDelete(LoginRequiredMixin, ValidateUnconnectedSectionsDeleteMixin, DeleteView):
    model = Instructor
    success_url = reverse_lazy('courseinfo:instructor_list')
    template_name = GENERIC_DELETE_TEMPLATE_PATH
    failed_delete_template = GENERIC_FAILED_DELETE_TEMPLATE_PATH


class SectionList(LoginRequiredMixin, ListView):
    model = Section
    context_object_name = 'section_list'


class SectionDetailView(LoginRequiredMixin, DetailView):
    model = Section

    def get_context_data(self, **kwargs):
        kwargs['students'] = self.get_object().students.all()
        kwargs['instructors'] = self.get_object().instructors.all()
        return super(SectionDetailView, self).get_context_data(**kwargs)


class SectionCreate(LoginRequiredMixin, CourseActionMixin, CreateView):
    model = Section
    success_msg = "Section Created!"
    form_class = SectionForm
    template_name = GENERIC_CRISPY_FORM_PATH

    def get_context_data(self, **kwargs):
        context = super(SectionCreate, self).get_context_data(**kwargs)
        context['page_title'] = 'Create Section'
        return context


class SectionUpdate(LoginRequiredMixin, CourseActionMixin, UpdateView):
    model = Section
    success_msg = "Section Updated!"
    form_class = SectionForm
    template_name = GENERIC_CRISPY_FORM_PATH

    def get_context_data(self, **kwargs):
        context = super(SectionUpdate, self).get_context_data(**kwargs)
        context['page_title'] = 'Update Section'
        return context


class SectionDelete(LoginRequiredMixin, DeleteView):
    model = Section
    success_url = reverse_lazy('courseinfo:section_list')
    template_name = GENERIC_DELETE_TEMPLATE_PATH

    def get_context_data(self, **kwargs):
        context = super(SectionDelete, self).get_context_data(**kwargs)
        context['page_title'] = 'Delete Instructor'
        return context


class CourseList(LoginRequiredMixin, ListView):
    model = Course
    context_object_name = 'course_list'


class CourseDetailView(LoginRequiredMixin, DetailView):
    model = Course

    def get_context_data(self, **kwargs):
        kwargs['sections'] = self.get_object().sections.all()
        return super(CourseDetailView, self).get_context_data(**kwargs)


class CourseCreate(LoginRequiredMixin, CourseActionMixin, CreateView):
    model = Course
    success_msg = "Course Created!"
    form_class = CourseForm
    template_name = GENERIC_CRISPY_FORM_PATH

    def get_context_data(self, **kwargs):
        context = super(CourseCreate, self).get_context_data(**kwargs)
        context['page_title'] = 'Create Course'
        return context


class CourseUpdate(LoginRequiredMixin, CourseActionMixin, UpdateView):
    model = Course
    success_msg = "Course Updated!"
    form_class = CourseForm
    template_name = GENERIC_CRISPY_FORM_PATH

    def get_context_data(self, **kwargs):
        context = super(CourseUpdate, self).get_context_data(**kwargs)
        context['page_title'] = 'Update Course'
        return context


class CourseDelete(LoginRequiredMixin, ValidateUnconnectedSectionsDeleteMixin, DeleteView):
    model = Course
    success_url = reverse_lazy('courseinfo:course_list')
    template_name = GENERIC_DELETE_TEMPLATE_PATH
    failed_delete_template = GENERIC_FAILED_DELETE_TEMPLATE_PATH


class SemesterList(LoginRequiredMixin, ListView):
    model = Semester
    context_object_name = 'semester_list'


class SemesterDetailView(LoginRequiredMixin, DetailView):
    model = Semester

    def get_context_data(self, **kwargs):
        kwargs['sections'] = self.get_object().sections.all()
        return super(SemesterDetailView, self).get_context_data(**kwargs)


class SemesterCreate(LoginRequiredMixin, CourseActionMixin, CreateView):
    model = Semester
    success_msg = "Semester Created!"
    form_class = SemesterForm
    template_name = GENERIC_CRISPY_FORM_PATH

    def get_context_data(self, **kwargs):
        context = super(SemesterCreate, self).get_context_data(**kwargs)
        context['page_title'] = 'Create Semester'
        return context


class SemesterUpdate(LoginRequiredMixin, CourseActionMixin, UpdateView):
    model = Semester
    success_msg = "Semester Updated!"
    form_class = SemesterForm
    template_name = GENERIC_CRISPY_FORM_PATH

    def get_context_data(self, **kwargs):
        context = super(SemesterUpdate, self).get_context_data(**kwargs)
        context['page_title'] = 'Update Semester'
        return context


class SemesterDelete(LoginRequiredMixin, ValidateUnconnectedSectionsDeleteMixin, DeleteView):
    model = Semester
    success_url = reverse_lazy('courseinfo:semester_list')
    template_name = GENERIC_DELETE_TEMPLATE_PATH
    failed_delete_template = GENERIC_FAILED_DELETE_TEMPLATE_PATH


class StudentList(LoginRequiredMixin, ListView):
    model = Student
    context_object_name = 'student_list'
    paginate_by = 5
    queryset = Student.objects.all()


class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Student

    def get_context_data(self, **kwargs):
        kwargs['sections'] = self.get_object().sections.all()
        return super(StudentDetailView, self).get_context_data(**kwargs)


class StudentCreate(LoginRequiredMixin, CourseActionMixin, CreateView):
    model = Student
    success_msg = "Student Created!"
    form_class = StudentForm
    template_name = GENERIC_CRISPY_FORM_PATH

    def get_context_data(self, **kwargs):
        context = super(StudentCreate, self).get_context_data(**kwargs)
        context['page_title'] = 'Create Student'
        return context


class StudentUpdate(LoginRequiredMixin, CourseActionMixin, UpdateView):
    model = Student
    success_msg = "Student Updated!"
    form_class = StudentForm
    template_name = GENERIC_CRISPY_FORM_PATH

    def get_context_data(self, **kwargs):
        context = super(StudentUpdate, self).get_context_data(**kwargs)
        context['page_title'] = 'Update Student'
        return context


class StudentDelete(LoginRequiredMixin, ValidateUnconnectedSectionsDeleteMixin, DeleteView):
    model = Student
    success_url = reverse_lazy('courseinfo:student_list')
    template_name = GENERIC_DELETE_TEMPLATE_PATH
    failed_delete_template = GENERIC_FAILED_DELETE_TEMPLATE_PATH

courseinfo/templates/courseinfo/course_list.html
{% extends 'courseinfo/courseinfo_base.html' %}

{% block title %}
  Course List
{% endblock %}

{% block extended_content %}
  <h2> Course List </h2>
  <div>
    <a class="btn btn-primary"
       href="{% url 'courseinfo:course_create' %}">
      Create New Course
    </a>
  </div>
  <br/>
  <ul>
    {%  for course in course_list %}
      <li>
        <a href="{{ course.get_absolute_url }}">{{ course }}</a>
      </li>
      {% empty %}
        <li><em>There are currently no courses available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

courseinfo/templates/courseinfo/courseinfo_base.html
{% extends 'base.html' %}

{% block content %}
  <main>
    {% block extended_content %}
{#      There is no real need for this anymore because the base.html file was updated project-wide.#}
    {% endblock %}
  </main>
{% endblock %}

courseinfo/templates/courseinfo/generic_confirm_delete.html
{% extends 'courseinfo/courseinfo_base.html' %}

{% block title %}
  {{ page_title|title }}
{% endblock %}

{% block extended_content %}
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <a href="{{ object.get_absolute_url }}"
       class="btn btn-success">
      Cancel
    </a>
    <input type="submit"
           class="btn btn-danger"
           value="Confirm" />
  </form>
  <br/>
{% endblock %}

courseinfo/templates/courseinfo/generic_crispy_form.html
{% extends 'courseinfo/courseinfo_base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  {{ page_title|title }}
{% endblock %}

{% block extended_content %}
  {% crispy form %}
{% endblock %}

courseinfo/templates/courseinfo/instructor_confirm_delete.html
{% extends 'courseinfo/courseinfo_base.html' %}

{% block title %}
  Remove Instructor
{% endblock %}

{% block extended_content %}
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

courseinfo/templates/courseinfo/instructor_detail.html
{% extends 'courseinfo/courseinfo_base.html' %}

{% block title %}
  Instructor - {{ instructor }}
{% endblock %}

{% block extended_content %}
  <h2> {{  instructor }} </h2>

  <div>
    <a class="btn btn-secondary" href="{{ instructor.get_update_url }}">
      Update Instructor
    </a>
    <a class="btn btn-danger" href="{{ instructor.get_delete_url }}">
      Remove Instructor
    </a>
  </div>

  <section>
    <h3>First Name</h3>
    <p>{{ instructor.first_name }}</p>
    <h3>Last Name</h3>
    <p>{{ instructor.last_name }}</p>
  </section>

  <section>
    <h3>Sections</h3>
    {%  for section in instructor.sections.all %}
      <li>
        <a href="{{ section.get_absolute_url }}">{{ section }}</a>
      </li>
      {% empty %}
        <li><em>{{  instructor }} is not currently teaching any sections. </em></li>
    {% endfor %}
  </section>
{% endblock %}

courseinfo/templates/courseinfo/instructor_list.html
{% extends 'courseinfo/courseinfo_base.html' %}

{% block title %}
  Instructor List
{% endblock %}

{% block extended_content %}
  <h2> Instructor List </h2>
  <div>
    <a class="btn btn-primary"
       href="{% url 'courseinfo:instructor_create' %}">
      Create New Instructor
    </a>
  </div>
  <br/>
  <ul>
    {%  for instructor in instructor_list %}
      <li>
        <a href="{{ instructor.get_absolute_url }}">{{ instructor }}</a>
      </li>
      {% empty %}
        <li><em>There are currently no instructors available.</em></li>
    {% endfor %}
  </ul>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }}<span class="sr-only">(current)</span></span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

courseinfo/templates/courseinfo/section_create.html
{% extends 'courseinfo/courseinfo_base.html' %}

{% block title %}
  Create Instructor
{% endblock %}

{% block extended_content %}
  {% load crispy_forms_tags %}
  {% crispy form %}
{% endblock %}

courseinfo/templates/courseinfo/section_detail.html
{% extends 'courseinfo/courseinfo_base.html' %}

{% block title %}
  Section - {{ section }}
{% endblock %}

{% block extended_content %}
  <h2> {{  section }} </h2>

  <div>
    <a class="btn btn-secondary" href="{{ section.get_update_url }}">
      Update Section
    </a>
    <a class="btn btn-danger" href="{{ section.get_delete_url }}">
      Remove Section
    </a>
  </div>

  <section>
    <br/>
    <h3>Section Name</h3>
    <p>{{ section.section_name }}</p>
    <br/>
    <h3>Semester</h3>
    <a  href="{{ section.semester.get_absolute_url }}">{{ section.semester }}</a>
    <p><br/></p>
    <h3>Course</h3>
    <a  href="{{ section.course.get_absolute_url }}">{{ section.course }}</a>
    <p><br/></p>

  </section>

 <section>

    <h2> Instructor List </h2>
    <ul>
      {%  for instructor in section.instructors.all %}
        <li>
          <a href="{{ instructor.get_absolute_url }}">{{ instructor }}</a>
        </li>
        {% empty %}
          <li><em>There are currently no instructors available.</em></li>
      {% endfor %}
    </ul>

    <br/>
    <h2> Student List </h2>
    <ul>
      {%  for student in section.students.all %}
        <li>
          <a href="{{ student.get_absolute_url }}">{{ student }}</a>
        </li>
        {% empty %}
          <li><em>There are currently no students available.</em></li>
      {% endfor %}
    </ul>
  </section>

{% endblock %}

courseinfo/templates/courseinfo/section_list.html
{% extends 'courseinfo/courseinfo_base.html' %}

{% block title %}
  Section List
{% endblock %}

{% block extended_content %}
  <h2> Section List </h2>
  <div>
    <a class="btn btn-primary"
       href="{% url 'courseinfo:section_create' %}">
      Create New Section
    </a>
  </div>

  <br/>
  <ul>
    {%  for section in section_list %}
      <li>
        <a href="{{ section.get_absolute_url }}">{{ section }}</a>
      </li>
      {% empty %}
        <li><em>There are currently no sections available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

courseinfo/templates/courseinfo/semester_detail.html
{% extends 'courseinfo/courseinfo_base.html' %}

{% block title %}
  Semester - {{ semester }}
{% endblock %}

{% block extended_content %}
  <h2> {{  semester }} </h2>

  <div>
    <a class="btn btn-secondary" href="{{ semester.get_delete_url }}">
      Update Semester
    </a>
    <a class="btn btn-danger" href="{{ semester.get_delete_url }}">
      Remove Semester
    </a>
  </div>

  <section>
    <br/>
    <h3>Semester Name</h3>
    <p>{{ semester.semester_name }}</p>
    <br/>
  </section>

  <section>
    <h2> Course and Section List </h2>
    <ul>
      {%  for section in semester.sections.all %}
        <li>
          <a href="{{ section.get_absolute_url }}">{{ section }}</a>
        </li>
        {% empty %}
          <li><em>There are currently no sections available.</em></li>
      {% endfor %}
    </ul>
  </section>

{% endblock %}

courseinfo/templates/courseinfo/semester_list.html
{% extends 'courseinfo/courseinfo_base.html' %}

{% block title %}
  Semester List
{% endblock %}

{% block extended_content %}
  <h2> Semester List </h2>
  <div>
    <a class="btn btn-primary"
       href="{% url 'courseinfo:semester_create' %}">
      Create New Semester
    </a>
  </div>
  <br/>
  <ul>
    {%  for semester in semester_list %}
      <li>
        <a href="{{ semester.get_absolute_url }}">{{ semester }}</a>
      </li>
      {% empty %}
        <li><em>There are currently no semesters available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

courseinfo/templates/courseinfo/student_detail.html
{% extends 'courseinfo/courseinfo_base.html' %}

{% block title %}
  Student - {{ student }}
{% endblock %}

{% block extended_content %}
  <h2> {{ student.last_name }}, {{ student.first_name }} </h2>

    <div>
    <a class="btn btn-secondary" href="{{ student.get_update_url }}">
      Update Student
    </a>
    <a class="btn btn-danger" href="{{ student.get_delete_url }}">
      Remove Student
    </a>
  </div>

  <section>
    <br/>
    <h3>Student Name</h3>
    <p>{{ student }}</p>
    <br/>
  </section>

  <section>
    <h2> Course and Section List </h2>
    <ul>
      {%  for section in student.sections.all %}
        <li>
          <a href="{{ section.get_absolute_url }}">{{ section }}</a>
        </li>
        {% empty %}
          <li><em>There are currently no students available.</em></li>
      {% endfor %}
    </ul>
  </section>

{% endblock %}

courseinfo/templates/courseinfo/student_list.html
{% extends 'courseinfo/courseinfo_base.html' %}

{% block title %}
  Student List
{% endblock %}

{% block extended_content %}
  <h2> Student List </h2>
  <div>
    <a class="btn btn-primary"
       href="{% url 'courseinfo:student_create' %}">
      Create New Student
    </a>
  </div>
  <br/>
  <ul>
    {%  for student in student_list %}
      <li>
        <a href="{{ student.get_absolute_url }}">{{ student }}</a>
      </li>
      {% empty %}
        <li><em>There are currently no students available.</em></li>
    {% endfor %}
  </ul>

  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active"><span class="page-link">{{ i }}<span class="sr-only">(current)</span></span></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
      {% endif %}
    </ul>
{% endif %}
{% endblock %}